### PR TITLE
Use svg icons for next & previous

### PR DESCRIPTION
**Pull request by femioladeji**

### CODE REVIEW

**Comment by femioladeji** [comment]
#28

**Comment by RamSailopal** [comment]
I've just built the lastest version into our app and the left and right buttons aren't appearing at all. The image references are lib/icons/left-arrow.svg and lib/icons/right-arrow.svg but we just get image place holders as opposed to the images themselves

**Comment by femioladeji** [comment]
Wow @RamSailopal can you give me few minutes to look into that? I'll get back to you soon

**Comment by RamSailopal** [comment]
If you navigate to https://philance.ddns.net you can see the issue on the front page. :+1:

**Comment by femioladeji** [comment]
Thanks for pointing this out @RamSailopal I've made a new release to fix the bug. 👍 🎉

**Pull request merged**
