### PR TITLE
Stop slideshow on mouse hover for the Slide mode.

### PR DESCRIPTION
**Pull request by calorenzo**
I've added a new parameter "stopOnHover" which defaults true to stop the slideshow displayed in Slide mode when the users hovers the mouse over it.

### CODE REVIEW

**Comment by femioladeji** [comment]
Nice one @calorenzo. It's really cool. Thanks for contributing.
Just a couple of things
1. Can you change it to `pauseOnHover`? I think that's a little more descriptive
2. Set the default to `false`
3. You only added it to the slide effect, can it be added to the zoom and fade effects as well
4. Add it to the properties list in the readme
5. Add the tests for it. For the slide effect, the spec can look like this

```
test('if stopOnHover is true, the slide pauses on mouse enter and resumes on mouseleave', async () => {
  const wrapperElement = document.createElement('div');
  const { baseElement } = renderSlide(
    { ...options, autoplay: true, stopOnHover: true},
    wrapperElement
  );
  // the slide stops on mouse enter
  fireEvent.mouseEnter(baseElement);
  await wait(
    () => {
      const childrenElements = baseElement.querySelectorAll(
        '.images-wrap > div'
      );
      expect(childrenElements[1].classList).toContain('active');
    },
    {
      timeout: options.duration + options.transitionDuration
    }
  );
  // the slide stops on mouse leave
  fireEvent.mouseLeave(baseElement);
  await wait(
    () => {
      const childrenElements = baseElement.querySelectorAll(
        '.images-wrap > div'
      );
      expect(childrenElements[2].classList).toContain('active');
      expect(childrenElements[1].classList.contains('active')).toBeFalsy();
    },
    {
      timeout: options.duration + options.transitionDuration
    }
  );
});
```

If you need my help with any of this just leave a comment

**Comment by calorenzo** [comment]
I've made the changes you suggested me:
- Property renamed to pauseOnHover.
- Property description added to the README file.
- Feature added to Slide, Fade and Zoom animations.
- Added tests to check the pauseOnHover feature in Slide, Fade and Zoom animations.

**Comment by femioladeji** [comment]
@calorenzo looks like you added some files again. Can you please check the PR again

**Comment by calorenzo** [comment]
Sorry for the inconvenience but this is my first time contributing here.
I can't understand what do you mean: I've added three commits to the PR each one with different files. The only one that I previously added is the slide.js and I need to commit it again in order to override the changes I made (stopOnHover --> pauseOnHover and so on).

**Comment by calorenzo** [comment]
Forget about it, I've just realized what do you mean. 
Sorry, I'm trying to put the files in the correct location.

**Comment by femioladeji** [comment]
@calorenzo can you please resolve the conflicts.

Don't bother about the failing tests

**Comment by calorenzo** [comment]
I've resolve the conflicts (I though I didn't have the permissions to do it previously).
Thank you for your feedback.

**Comment by femioladeji** [comment]
@calorenzo sorry for the back and forth. I think we're almost there. Just one last thing. If you check the files changed you'll see that there are some lines that changed even though there's actually no change. Can you please look into that.

If you check the change in the test files you will see that it's accurate, but the change in the  other files have some slight issues. Maybe you need to pull from upstream so that your branch will be up to date. Let me know if you need any help with that

**Comment by calorenzo** [comment]
Ok, I've found the problem was the newline character that got changed in everyline for some files.
I've fixed it, hope now it's ok.
Thank you for your feedback.

**Comment by femioladeji** [comment]
Nice one @calorenzo

**Comment by femioladeji** [comment]
I've released a new version that includes your feature. Thanks for contributing

👍 👍 👍

**Pull request merged**
