### PR TITLE
canSwipe - new props for slide.js

### PR DESCRIPTION
**Pull request by branislavblazek**
Not every user wants to slide current slideitem when he drag that with mouse.

### CODE REVIEW

**Comment by femioladeji** [comment]
@branislavblazek thanks for your contribution. You'll still have to do few more things though.

You need to add the prop after [this line](https://github.com/femioladeji/react-slideshow/blob/master/src/props.js#L11) and set it to `true` by default.
You also have to add it after [this line](https://github.com/femioladeji/react-slideshow/blob/master/src/props.js#L32) and set it to `boolean`
Then add it to the doc [here](https://github.com/femioladeji/react-slideshow/blob/master/src/props.js#L32)

**Comment by vagnerkuntz** [comment]
@femioladeji, I added the lines you said
anyway it doesn't work

**Comment by femioladeji** [comment]
@vagnerkuntz can you push what you have and then I'll take a look at the PR again and make the necessary modifications

**Comment by branislavblazek** [comment]
I am new to editing packages, i want to make your package more powerful and useable for more people but idk how to edit that on my machine. How can test what i have changed? I have git clonned this repo bud idk in what file i have to start with my changes. Can u please help me with this?

**Comment by femioladeji** [comment]
@branislavblazek you can run `yarn dev` command on your machine. With that, you will be able to run the docs locally and see this `https://react-slideshow.herokuapp.com/`. The main package source code is in the `src` folder and the documentation is in the `docs` folder. Let me know if you still need any more help

**Pull request closed without merging**
