### PR TITLE
Add callback executed when slide/fade/zoom end

### PR DESCRIPTION
**Pull request by Hinaser**
Currently z-index of each slide is not set.
When you want to add button on each slide, because of z-index unset, you cannot click the button.

To resolve this issue, I added `onChange` props to components.

Expected usage
```
<Fade onChange={ (oldIndex, newIndex) => {
             // Change z-index of oldIndex to 0
             ...
             // Change z-index of newIndex to 1
             ...
           }}
      {...props}
>
...
</Fade>
```

### CODE REVIEW

**Comment by andela-foladeji** [comment]
@Hinaser I think an easier approach will be to do this `style={{opacity: key === index ? '1' : '0', zIndex: key === index ? '1' : '0'}}` on this [line](https://github.com/andela-foladeji/react-slideshow/blob/master/src/lib/components/slideshow/fade.js#L87). Can you try that out and let me know if it worked perfectly for you?

**Comment by andela-foladeji** [comment]
@Hinaser 
I was thinking about this and I got a little bit confused.
> What changed my mind is that there may be another container whose z-index is larger than 1.

Are you saying if we have something like this
```js
<div className="slide-container fade-container" style={{zIndex: 100}}>
  <Fade {...fadeProperties}>
  <div className="each-fade">
    <div className="image-container">
    <img src={fadeImages[0]} />
    </div>
    <h2><input type="button" value="first button" onClick={this.clicked} /></h2>
  </div>
  <div className="each-fade">
  <h2><input type="button" value="second button" onClick={this.clicked} /></h2>
    <div className="image-container">
    <img src={fadeImages[1]} />
    </div>
  </div>
  <div className="each-fade">
    <div className="image-container">
    <img src={fadeImages[2]} />
    </div>
    <h2><input type="button" value="Third button" onClick={this.clicked} /></h2>
  </div>
  </Fade>
</div>
```
it won't work?

I don't think that will be an issue since it's just a container, it won't stop the buttons from being clickable.

**Comment by Hinaser** [comment]
Hi @andela-foladeji 

Slightly different to my thinking.

This is it.

```
<Fade {...fadeProperties}>
  <div className="each-fade">
    <div className="image-container">
    <img src={fadeImages[0]} />
    </div>
    <h2><input type="button" value="first button" onClick={this.clicked} /></h2>
  </div>
  ...
</Fade>
<div style='z-index: 100; position: absolute; top: ..., left: ...'>
 Some container which disturbs <Fade />.
 This container is next to <Fade /> and may overlay <Fade />.
</div>
```

**Comment by andela-foladeji** [comment]
@Hinaser ok I get that now but if someone does that is it not safe to assume that they actually want portion of the div to probably overlay the fade and I don't think that scenario will occur regularly

**Pull request closed without merging**
